version: "3"

services:
  ui:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    container_name: mean-angular
    networks:
      - mean-stack-net
    # volumes:
    #   - ./Angular/src:/usr/app/src
    #   - ./Angular/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    container_name: mean-api
    networks:
      - mean-stack-net
    # volumes:
    #   - ./API/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mean-mongo
    networks:
      - mean-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mean-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local