version: "3.8"

services:
  ui:
    build: angular
    container_name: mean_angular
    ports:
      - 4200:4200
    networks:
      - taw_unnamed_network
    volumes:
      - ./angular/src:/usr/app/src
      - ./angular/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build: api
    container_name: mean_api
    ports:
      - 3080:3080
    networks:
      - taw_unnamed_network
    volumes:
      - ./api/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    container_name: mean_mongo
    # restart: always
    ports:
      - 27017:27017
    networks:
      - taw_unnamed_network
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx
    container_name: mean_nginx
    # restart: always
    ports:
      - 80:80
    networks:
      - taw_unnamed_network

  redis:
    image: redis
    container_name: mean_redis
    networks:
      - taw_unnamed_network

networks:
  taw_unnamed_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local