version: "3.8"

services:
  ui:
    build: angular
    container_name: mean_angular
    ports:
      - 4200:4200
    networks:
      - reservabyte_network
    volumes:
      - ./angular/src:/usr/app/src
      - ./angular/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build: api
    container_name: mean_api
    ports:
      - 3080:3080
    networks:
      - reservabyte_network
    volumes:
      - ./api/src:/usr/app/src
      - ./db:/usr/app/mongo-data
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mongo
    container_name: mean_mongo
    ports:
      - 27017:27017
    networks:
      - reservabyte_network
    volumes:
      - mongo-data:/data/db

  # nginx:
  #   image: nginx
  #   container_name: mean_nginx
  #   ports:
  #     - 80:80
  #   networks:
  #     - reservabyte_network

  # redis:
  #   image: redis
  #   container_name: mean_redis
  #   networks:
  #     - reservabyte_network

networks:
  reservabyte_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local